export const TENANCY_REPOSITORY = Symbol('TENANCY_REPOSITORY');
export const CREATE_TENANCY_SERVICE = Symbol('CREATE_TENANCY_SERVICE');
export const LIST_TENANCIES_SERVICE = Symbol('LIST_TENANCIES_SERVICE');
