export const FONTE_REPOSITORY = Symbol('FONTE_REPOSITORY');
export const CREATE_FONTE_SERVICE = Symbol('CREATE_FONTE_SERVICE');
export const LIST_FONTES_SERVICE = Symbol('LIST_FONTES_SERVICE');
export const GET_FONTE_SERVICE = Symbol('GET_FONTE_SERVICE');
export const UPDATE_FONTE_SERVICE = Symbol('UPDATE_FONTE_SERVICE');
export const DELETE_FONTE_SERVICE = Symbol('DELETE_FONTE_SERVICE');
export const VALIDATE_FONTE_ATIVA_SERVICE = Symbol('VALIDATE_FONTE_ATIVA_SERVICE');
