export const ESTAGIO_REPOSITORY = Symbol('ESTAGIO_REPOSITORY');
export const ESTAGIOS_SERVICE = Symbol('ESTAGIOS_SERVICE');
export const MEDICAO_REPOSITORY = Symbol('MEDICAO_REPOSITORY');
export const MEDICOES_SERVICE = Symbol('MEDICOES_SERVICE');
