export enum TipoPessoa {
  FISICA = 'FISICA',
  JURIDICA = 'JURIDICA',
}

export enum ConselhoProfissional {
  CREA = 'CREA',
  CAU = 'CAU',
  CFT = 'CFT',
}

export enum OrigemGeolocalizacao {
  MANUAL = 'MANUAL',
  GPS_DISPOSITIVO = 'GPS_DISPOSITIVO',
  CEP = 'CEP',
}

export enum SituacaoAlvara {
  SEM_ALVARA = 'SEM_ALVARA',
  COM_ALVARA_VIGENTE = 'COM_ALVARA_VIGENTE',
  COM_ALVARA_VENCIDO = 'COM_ALVARA_VENCIDO',
  DISPENSADA = 'DISPENSADA',
}

export enum AndamentoObraPrivada {
  NAO_INICIADA = 'NAO_INICIADA',
  EM_ANDAMENTO = 'EM_ANDAMENTO',
  PARALISADA = 'PARALISADA',
  CONCLUIDA = 'CONCLUIDA',
  DEMOLIDA = 'DEMOLIDA',
  CANCELADA = 'CANCELADA',
}

export enum SituacaoHabiteSe {
  NAO_SOLICITADO = 'NAO_SOLICITADO',
  SOLICITADO = 'SOLICITADO',
  APROVADO = 'APROVADO',
  REPROVADO = 'REPROVADO',
}

export enum EtapaObraPrivada {
  NAO_INICIADA = 'NAO_INICIADA',
  FUNDACAO = 'FUNDACAO',
  ESTRUTURA = 'ESTRUTURA',
  ALVENARIA = 'ALVENARIA',
  COBERTURA = 'COBERTURA',
  INSTALACOES = 'INSTALACOES',
  ACABAMENTO = 'ACABAMENTO',
  CONCLUIDA = 'CONCLUIDA',
}

export enum TipoAlvara {
  CONSTRUCAO = 'CONSTRUCAO',
  REFORMA = 'REFORMA',
  AMPLIACAO = 'AMPLIACAO',
  DEMOLICAO = 'DEMOLICAO',
  REGULARIZACAO = 'REGULARIZACAO',
  MURO_TAPUME = 'MURO_TAPUME',
}

export enum MotivoAlvara {
  ORIGINAL = 'ORIGINAL',
  REVALIDACAO = 'REVALIDACAO',
  PRORROGACAO = 'PRORROGACAO',
  SEGUNDA_VIA = 'SEGUNDA_VIA',
}

export enum SituacaoRegistroAlvara {
  VIGENTE = 'VIGENTE',
  SUBSTITUIDO = 'SUBSTITUIDO',
  VENCIDO = 'VENCIDO',
  INDEFERIDO = 'INDEFERIDO',
}

export enum UsoEdificacao {
  RESIDENCIAL_UNIFAMILIAR = 'RESIDENCIAL_UNIFAMILIAR',
  RESIDENCIAL_MULTIFAMILIAR = 'RESIDENCIAL_MULTIFAMILIAR',
  COMERCIAL = 'COMERCIAL',
  INDUSTRIAL = 'INDUSTRIAL',
  MISTO = 'MISTO',
  OUTRO = 'OUTRO',
}

export enum ResultadoHabiteSe {
  APROVADO = 'APROVADO',
  REPROVADO = 'REPROVADO',
}

export enum TipoFiscalizacao {
  ROTINA = 'ROTINA',
  DENUNCIA = 'DENUNCIA',
  ENTULHO = 'ENTULHO',
  VERIFICACAO_ALVARA = 'VERIFICACAO_ALVARA',
  VISTORIA_HABITE_SE = 'VISTORIA_HABITE_SE',
  REINCIDENCIA = 'REINCIDENCIA',
}

export enum ResultadoFiscalizacao {
  REGULAR = 'REGULAR',
  IRREGULAR = 'IRREGULAR',
  NAO_LOCALIZADA = 'NAO_LOCALIZADA',
  SEM_ACESSO = 'SEM_ACESSO',
}

export enum LocalEntulho {
  VIA_PUBLICA = 'VIA_PUBLICA',
  PASSEIO = 'PASSEIO',
  TERRENO_VIZINHO = 'TERRENO_VIZINHO',
  CANTEIRO = 'CANTEIRO',
  AREA_PROTEGIDA = 'AREA_PROTEGIDA',
}

export enum TipoAutoInfracao {
  NOTIFICACAO = 'NOTIFICACAO',
  AUTO_INFRACAO = 'AUTO_INFRACAO',
  EMBARGO = 'EMBARGO',
  INTERDICAO = 'INTERDICAO',
  MULTA = 'MULTA',
}

export enum SituacaoAutoInfracao {
  ABERTO = 'ABERTO',
  CUMPRIDO = 'CUMPRIDO',
  EM_RECURSO = 'EM_RECURSO',
  CANCELADO = 'CANCELADO',
  QUITADO = 'QUITADO',
}

export enum PapelResponsavelTecnico {
  PROJETO_ARQUITETONICO = 'PROJETO_ARQUITETONICO',
  PROJETO_ESTRUTURAL = 'PROJETO_ESTRUTURAL',
  PROJETO_COMPLEMENTAR = 'PROJETO_COMPLEMENTAR',
  EXECUCAO = 'EXECUCAO',
}

export enum TipoDocumentoResponsabilidade {
  ART = 'ART',
  RRT = 'RRT',
  TRT = 'TRT',
}

export enum VinculoArquivoPrivado {
  OBRA = 'OBRA',
  FISCALIZACAO = 'FISCALIZACAO',
  ALVARA = 'ALVARA',
  HABITE_SE = 'HABITE_SE',
  AUTO_INFRACAO = 'AUTO_INFRACAO',
  ART_RRT = 'ART_RRT',
}

export enum CategoriaArquivoPrivado {
  FOTO = 'FOTO',
  DOCUMENTO = 'DOCUMENTO',
  PROJETO = 'PROJETO',
}

export enum TipoEventoTimeline {
  ALVARA = 'ALVARA',
  FISCALIZACAO = 'FISCALIZACAO',
  FISCALIZACAO_IRREGULAR = 'FISCALIZACAO_IRREGULAR',
  AUTO = 'AUTO',
  EMBARGO = 'EMBARGO',
  HABITE_SE = 'HABITE_SE',
  OBSERVACAO = 'OBSERVACAO',
}
