export const OBRA_PRIVADA_REPOSITORY = Symbol('OBRA_PRIVADA_REPOSITORY');
export const CREATE_OBRA_PRIVADA_SERVICE = Symbol(
  'CREATE_OBRA_PRIVADA_SERVICE',
);
export const LISTAR_OBRAS_SERVICE = Symbol('LISTAR_OBRAS_SERVICE');
export const DETALHAR_OBRA_SERVICE = Symbol('DETALHAR_OBRA_SERVICE');
export const ATUALIZAR_OBRA_SERVICE = Symbol('ATUALIZAR_OBRA_SERVICE');
export const EXCLUIR_OBRA_SERVICE = Symbol('EXCLUIR_OBRA_SERVICE');
export const LISTAR_FISCALIZACOES_GLOBAL_SERVICE = Symbol(
  'LISTAR_FISCALIZACOES_GLOBAL_SERVICE',
);
export const LISTAR_AUTOS_GLOBAL_SERVICE = Symbol(
  'LISTAR_AUTOS_GLOBAL_SERVICE',
);
export const RESUMIR_AUTOS_SERVICE = Symbol('RESUMIR_AUTOS_SERVICE');
export const LISTAR_LICENCIAMENTO_SERVICE = Symbol(
  'LISTAR_LICENCIAMENTO_SERVICE',
);
export const ALVARA_REPOSITORY = Symbol('ALVARA_REPOSITORY');
export const CREATE_ALVARA_SERVICE = Symbol('CREATE_ALVARA_SERVICE');
export const LIST_ALVARAS_SERVICE = Symbol('LIST_ALVARAS_SERVICE');
export const UPDATE_ALVARA_SERVICE = Symbol('UPDATE_ALVARA_SERVICE');
export const DELETE_ALVARA_SERVICE = Symbol('DELETE_ALVARA_SERVICE');
export const FISCALIZACAO_REPOSITORY = Symbol('FISCALIZACAO_REPOSITORY');
export const CREATE_FISCALIZACAO_SERVICE = Symbol(
  'CREATE_FISCALIZACAO_SERVICE',
);
export const LIST_FISCALIZACOES_SERVICE = Symbol('LIST_FISCALIZACOES_SERVICE');
export const UPDATE_FISCALIZACAO_SERVICE = Symbol(
  'UPDATE_FISCALIZACAO_SERVICE',
);
export const DELETE_FISCALIZACAO_SERVICE = Symbol(
  'DELETE_FISCALIZACAO_SERVICE',
);
export const DETALHAR_FISCALIZACAO_SERVICE = Symbol(
  'DETALHAR_FISCALIZACAO_SERVICE',
);
export const OBRA_PRIVADA_OBSERVACAO_REPOSITORY = Symbol(
  'OBRA_PRIVADA_OBSERVACAO_REPOSITORY',
);
export const CREATE_OBRA_PRIVADA_OBSERVACAO_SERVICE = Symbol(
  'CREATE_OBRA_PRIVADA_OBSERVACAO_SERVICE',
);
export const LIST_OBRA_PRIVADA_OBSERVACOES_SERVICE = Symbol(
  'LIST_OBRA_PRIVADA_OBSERVACOES_SERVICE',
);
export const DELETE_OBRA_PRIVADA_OBSERVACAO_SERVICE = Symbol(
  'DELETE_OBRA_PRIVADA_OBSERVACAO_SERVICE',
);

export const AUTO_INFRACAO_REPOSITORY = Symbol('AUTO_INFRACAO_REPOSITORY');
export const CREATE_AUTO_INFRACAO_SERVICE = Symbol(
  'CREATE_AUTO_INFRACAO_SERVICE',
);
export const LIST_AUTOS_INFRACAO_SERVICE = Symbol(
  'LIST_AUTOS_INFRACAO_SERVICE',
);
export const UPDATE_AUTO_INFRACAO_SERVICE = Symbol(
  'UPDATE_AUTO_INFRACAO_SERVICE',
);

export const HABITE_SE_REPOSITORY = Symbol('HABITE_SE_REPOSITORY');
export const CREATE_HABITE_SE_SERVICE = Symbol('CREATE_HABITE_SE_SERVICE');
export const LIST_HABITE_SE_SERVICE = Symbol('LIST_HABITE_SE_SERVICE');
export const UPDATE_HABITE_SE_SERVICE = Symbol('UPDATE_HABITE_SE_SERVICE');
export const DELETE_HABITE_SE_SERVICE = Symbol('DELETE_HABITE_SE_SERVICE');
export const LIST_OBRAS_NO_MESMO_IMOVEL_SERVICE = Symbol(
  'LIST_OBRAS_NO_MESMO_IMOVEL_SERVICE',
);
export const LIST_OBRA_PRIVADA_ETAPAS_SERVICE = Symbol(
  'LIST_OBRA_PRIVADA_ETAPAS_SERVICE',
);
export const LIST_OBRA_PRIVADA_TIMELINE_SERVICE = Symbol(
  'LIST_OBRA_PRIVADA_TIMELINE_SERVICE',
);

export const OBRA_PRIVADA_RESPONSAVEL_REPOSITORY = Symbol(
  'OBRA_PRIVADA_RESPONSAVEL_REPOSITORY',
);
export const CREATE_OBRA_PRIVADA_RESPONSAVEL_SERVICE = Symbol(
  'CREATE_OBRA_PRIVADA_RESPONSAVEL_SERVICE',
);
export const LIST_OBRA_PRIVADA_RESPONSAVEIS_SERVICE = Symbol(
  'LIST_OBRA_PRIVADA_RESPONSAVEIS_SERVICE',
);
export const UPDATE_OBRA_PRIVADA_RESPONSAVEL_SERVICE = Symbol(
  'UPDATE_OBRA_PRIVADA_RESPONSAVEL_SERVICE',
);
export const DELETE_OBRA_PRIVADA_RESPONSAVEL_SERVICE = Symbol(
  'DELETE_OBRA_PRIVADA_RESPONSAVEL_SERVICE',
);

export const OBRA_PRIVADA_ARQUIVO_REPOSITORY = Symbol(
  'OBRA_PRIVADA_ARQUIVO_REPOSITORY',
);
export const INICIAR_UPLOAD_ARQUIVO_SERVICE = Symbol(
  'INICIAR_UPLOAD_ARQUIVO_SERVICE',
);
export const CONFIRMAR_UPLOAD_ARQUIVO_SERVICE = Symbol(
  'CONFIRMAR_UPLOAD_ARQUIVO_SERVICE',
);
export const LISTAR_ARQUIVOS_SERVICE = Symbol('LISTAR_ARQUIVOS_SERVICE');
export const OBTER_ARQUIVO_DOWNLOAD_URL_SERVICE = Symbol(
  'OBTER_ARQUIVO_DOWNLOAD_URL_SERVICE',
);
export const EDITAR_ARQUIVO_SERVICE = Symbol('EDITAR_ARQUIVO_SERVICE');
export const EXCLUIR_ARQUIVO_SERVICE = Symbol('EXCLUIR_ARQUIVO_SERVICE');
export const GERAR_RELATORIO_LISTA_OBRAS_PRIVADAS_SERVICE = Symbol(
  'GERAR_RELATORIO_LISTA_OBRAS_PRIVADAS_SERVICE',
);
export const GERAR_DOSSIE_OBRA_PRIVADA_SERVICE = Symbol(
  'GERAR_DOSSIE_OBRA_PRIVADA_SERVICE',
);
export const GERAR_RELATORIO_FISCALIZACAO_PRIVADA_SERVICE = Symbol(
  'GERAR_RELATORIO_FISCALIZACAO_PRIVADA_SERVICE',
);
