export const ATTACHMENT_REPOSITORY = Symbol('ATTACHMENT_REPOSITORY');
export const STORAGE_SERVICE = Symbol('STORAGE_SERVICE');
export const UPLOAD_ATTACHMENT_SERVICE = Symbol('UPLOAD_ATTACHMENT_SERVICE');
export const UPLOAD_ATTACHMENTS_BATCH_SERVICE = Symbol(
  'UPLOAD_ATTACHMENTS_BATCH_SERVICE',
);
export const REPLACE_ATTACHMENT_SERVICE = Symbol('REPLACE_ATTACHMENT_SERVICE');
export const DELETE_ATTACHMENT_SERVICE = Symbol('DELETE_ATTACHMENT_SERVICE');
export const GET_ATTACHMENT_DOWNLOAD_URL_SERVICE = Symbol(
  'GET_ATTACHMENT_DOWNLOAD_URL_SERVICE',
);
