export enum EstagioStatus { PENDENTE = 'PENDENTE', EM_ANDAMENTO = 'EM_ANDAMENTO', CONCLUIDO = 'CONCLUIDO' }
export enum ModoDuracao { NAO_INFORMADO = 'NAO_INFORMADO', DIAS_CORRIDOS = 'DIAS_CORRIDOS' }
export enum TipoMedicao { NORMAL = 'NORMAL', RETIFICACAO = 'RETIFICACAO', EXTRA = 'EXTRA', REAJUSTAMENTO = 'REAJUSTAMENTO' }
