export const PASTA_REPOSITORY = Symbol('PASTA_REPOSITORY');
export const ARQUIVO_REPOSITORY = Symbol('ARQUIVO_REPOSITORY');
export const GARANTIR_PASTA_RAIZ_SERVICE = Symbol(
  'GARANTIR_PASTA_RAIZ_SERVICE',
);
export const CRIAR_PASTA_SERVICE = Symbol('CRIAR_PASTA_SERVICE');
export const LISTAR_CONTEUDO_SERVICE = Symbol('LISTAR_CONTEUDO_SERVICE');
export const INICIAR_UPLOAD_SERVICE = Symbol('INICIAR_UPLOAD_SERVICE');
export const UPLOAD_DIRETO_SERVICE = Symbol('UPLOAD_DIRETO_SERVICE');
export const CONFIRMAR_UPLOAD_SERVICE = Symbol('CONFIRMAR_UPLOAD_SERVICE');
export const GERAR_DOWNLOAD_SERVICE = Symbol('GERAR_DOWNLOAD_SERVICE');
export const EDITAR_ARQUIVO_SERVICE = Symbol('EDITAR_ARQUIVO_SERVICE');
export const MOVER_ARQUIVO_SERVICE = Symbol('MOVER_ARQUIVO_SERVICE');
export const REMOVER_ARQUIVO_SERVICE = Symbol('REMOVER_ARQUIVO_SERVICE');
export const REMOVER_PASTA_SERVICE = Symbol('REMOVER_PASTA_SERVICE');
export const DUPLICAR_ARVORE_SERVICE = Symbol('DUPLICAR_ARVORE_SERVICE');
export const CONTAR_ARQUIVOS_SERVICE = Symbol('CONTAR_ARQUIVOS_SERVICE');
