export const RELATORIOS_QUERY = Symbol('RELATORIOS_QUERY');
export const LISTAR_OBRAS_RELATORIO_SERVICE = Symbol(
  'LISTAR_OBRAS_RELATORIO_SERVICE',
);
export const LISTAR_MAPA_OBRAS_RELATORIO_SERVICE = Symbol(
  'LISTAR_MAPA_OBRAS_RELATORIO_SERVICE',
);
export const LISTAR_CALENDARIO_OBRAS_RELATORIO_SERVICE = Symbol(
  'LISTAR_CALENDARIO_OBRAS_RELATORIO_SERVICE',
);
export const QUANTIFICADORES_RELATORIO_SERVICE = Symbol(
  'QUANTIFICADORES_RELATORIO_SERVICE',
);
export const DESEMPENHO_OBRA_RELATORIO_SERVICE = Symbol(
  'DESEMPENHO_OBRA_RELATORIO_SERVICE',
);
export const DASHBOARD_RELATORIO_SERVICE = Symbol(
  'DASHBOARD_RELATORIO_SERVICE',
);
export const FLUXO_FISICO_FINANCEIRO_RELATORIO_SERVICE = Symbol(
  'FLUXO_FISICO_FINANCEIRO_RELATORIO_SERVICE',
);
export const EXPORTAR_LISTA_OBRAS_RELATORIO_SERVICE = Symbol(
  'EXPORTAR_LISTA_OBRAS_RELATORIO_SERVICE',
);
export const GERAR_RELATORIO_OBRA_SERVICE = Symbol(
  'GERAR_RELATORIO_OBRA_SERVICE',
);
export const GERAR_DOSSIE_OBRA_SERVICE = Symbol('GERAR_DOSSIE_OBRA_SERVICE');
export const PDF_RENDERER = Symbol('PDF_RENDERER');
export const DOSSIE_OBRA_REPOSITORY = Symbol('DOSSIE_OBRA_REPOSITORY');
