export const EMPRESA_CONTRATADA_REPOSITORY = Symbol(
  'EMPRESA_CONTRATADA_REPOSITORY',
);
export const CONTRATO_REPOSITORY = Symbol('CONTRATO_REPOSITORY');
export const ADITIVO_REPOSITORY = Symbol('ADITIVO_REPOSITORY');
export const PARALISACAO_REPOSITORY = Symbol('PARALISACAO_REPOSITORY');

export const CREATE_CONTRATO_USE_CASE = Symbol('CREATE_CONTRATO_USE_CASE');
export const LIST_CONTRATOS_USE_CASE = Symbol('LIST_CONTRATOS_USE_CASE');
export const GET_CONTRATO_USE_CASE = Symbol('GET_CONTRATO_USE_CASE');
export const UPDATE_CONTRATO_USE_CASE = Symbol('UPDATE_CONTRATO_USE_CASE');
export const DELETE_CONTRATO_USE_CASE = Symbol('DELETE_CONTRATO_USE_CASE');
export const GET_PRAZO_FINAL_CONTRATO_USE_CASE = Symbol(
  'GET_PRAZO_FINAL_CONTRATO_USE_CASE',
);
export const GET_VALORES_CONTRATO_USE_CASE = Symbol(
  'GET_VALORES_CONTRATO_USE_CASE',
);

export const CREATE_EMPRESA_CONTRATADA_USE_CASE = Symbol(
  'CREATE_EMPRESA_CONTRATADA_USE_CASE',
);
export const LIST_EMPRESAS_CONTRATADAS_USE_CASE = Symbol(
  'LIST_EMPRESAS_CONTRATADAS_USE_CASE',
);
export const GET_EMPRESA_CONTRATADA_USE_CASE = Symbol(
  'GET_EMPRESA_CONTRATADA_USE_CASE',
);
export const UPDATE_EMPRESA_CONTRATADA_USE_CASE = Symbol(
  'UPDATE_EMPRESA_CONTRATADA_USE_CASE',
);
export const DELETE_EMPRESA_CONTRATADA_USE_CASE = Symbol(
  'DELETE_EMPRESA_CONTRATADA_USE_CASE',
);

export const CREATE_ADITIVO_USE_CASE = Symbol('CREATE_ADITIVO_USE_CASE');
export const LIST_ADITIVOS_USE_CASE = Symbol('LIST_ADITIVOS_USE_CASE');
export const GET_ADITIVO_USE_CASE = Symbol('GET_ADITIVO_USE_CASE');
export const DELETE_ADITIVO_USE_CASE = Symbol('DELETE_ADITIVO_USE_CASE');

export const CREATE_PARALISACAO_USE_CASE = Symbol(
  'CREATE_PARALISACAO_USE_CASE',
);
export const LIST_PARALISACOES_USE_CASE = Symbol('LIST_PARALISACOES_USE_CASE');
export const REINICIAR_PARALISACAO_USE_CASE = Symbol(
  'REINICIAR_PARALISACAO_USE_CASE',
);
export const DELETE_PARALISACAO_USE_CASE = Symbol(
  'DELETE_PARALISACAO_USE_CASE',
);
