export const EMPRESA_CONTRATADA_REPOSITORY = Symbol(
  'EMPRESA_CONTRATADA_REPOSITORY',
);
export const CONTRATO_REPOSITORY = Symbol('CONTRATO_REPOSITORY');
export const ADITIVO_REPOSITORY = Symbol('ADITIVO_REPOSITORY');
export const PARALISACAO_REPOSITORY = Symbol('PARALISACAO_REPOSITORY');
export const CREATE_CONTRATO_SERVICE = Symbol('CREATE_CONTRATO_SERVICE');
export const LIST_CONTRATOS_SERVICE = Symbol('LIST_CONTRATOS_SERVICE');
export const ADITIVOS_SERVICE = Symbol('ADITIVOS_SERVICE');
export const PARALISACOES_SERVICE = Symbol('PARALISACOES_SERVICE');
export const EMPRESAS_CONTRATADAS_SERVICE = Symbol(
  'EMPRESAS_CONTRATADAS_SERVICE',
);
