export default abstract class ErrorCodeConstants {
  static readonly UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';

  static readonly USER_NOT_FOUND = 'USER_NOT_FOUND';

  static readonly USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';

  static readonly USER_REPOSITORY_FAILED = 'USER_REPOSITORY_FAILED';

  static readonly USER_CREATE_FORBIDDEN = 'USER_CREATE_FORBIDDEN';

  static readonly USER_CREATE_FAILED = 'USER_CREATE_FAILED';

  static readonly USER_INVALID_NAME = 'USER_INVALID_NAME';

  static readonly USER_INVALID_EMAIL = 'USER_INVALID_EMAIL';

  static readonly USER_INVALID_PASSWORD = 'USER_INVALID_PASSWORD';

  static readonly USER_INVALID_TENANT = 'USER_INVALID_TENANT';

  static readonly TENANCY_INVALID_NAME = 'TENANCY_INVALID_NAME';

  static readonly TENANCY_INVALID_SLUG = 'TENANCY_INVALID_SLUG';

  static readonly TENANCY_INVALID_CNPJ = 'TENANCY_INVALID_CNPJ';

  static readonly TENANCY_INVALID_SCHEMA = 'TENANCY_INVALID_SCHEMA';

  static readonly TENANCY_PROVISION_FAILED = 'TENANCY_PROVISION_FAILED';

  static readonly TENANCY_CREATE_FAILED = 'TENANCY_CREATE_FAILED';

  static readonly TENANCY_CREATE_FORBIDDEN = 'TENANCY_CREATE_FORBIDDEN';

  static readonly AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND';

  static readonly AUTH_SESSION_REPOSITORY_FAILED = 'AUTH_SESSION_REPOSITORY_FAILED';

  static readonly AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';

  static readonly AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

  static readonly AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN';

  static readonly AUTH_REFRESH_FAILED = 'AUTH_REFRESH_FAILED';

  static readonly TENANT_CONTEXT_REQUIRED = 'TENANT_CONTEXT_REQUIRED';
}
