export default abstract class ErrorCodeConstants {
  static readonly UNEXPECTED_ERROR = 'UNEXPECTED_ERROR';

  static readonly USER_NOT_FOUND = 'USER_NOT_FOUND';

  static readonly USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS';

  static readonly USER_REPOSITORY_FAILED = 'USER_REPOSITORY_FAILED';

  static readonly USER_CREATE_FORBIDDEN = 'USER_CREATE_FORBIDDEN';

  static readonly USER_CREATE_FAILED = 'USER_CREATE_FAILED';

  static readonly USER_INVALID_NAME = 'USER_INVALID_NAME';

  static readonly USER_INVALID_EMAIL = 'USER_INVALID_EMAIL';

  static readonly USER_INVALID_PASSWORD = 'USER_INVALID_PASSWORD';

  static readonly USER_INVALID_TENANT = 'USER_INVALID_TENANT';

  static readonly TENANCY_INVALID_NAME = 'TENANCY_INVALID_NAME';

  static readonly TENANCY_INVALID_SLUG = 'TENANCY_INVALID_SLUG';

  static readonly TENANCY_INVALID_CNPJ = 'TENANCY_INVALID_CNPJ';

  static readonly TENANCY_INVALID_SCHEMA = 'TENANCY_INVALID_SCHEMA';

  static readonly TENANCY_PROVISION_FAILED = 'TENANCY_PROVISION_FAILED';

  static readonly TENANCY_CREATE_FAILED = 'TENANCY_CREATE_FAILED';

  static readonly TENANCY_CREATE_FORBIDDEN = 'TENANCY_CREATE_FORBIDDEN';
  static readonly TENANCY_LIST_FORBIDDEN = 'TENANCY_LIST_FORBIDDEN';

  static readonly AUTH_SESSION_NOT_FOUND = 'AUTH_SESSION_NOT_FOUND';

  static readonly AUTH_SESSION_REPOSITORY_FAILED =
    'AUTH_SESSION_REPOSITORY_FAILED';

  static readonly AUTH_INVALID_CREDENTIALS = 'AUTH_INVALID_CREDENTIALS';

  static readonly AUTH_LOGIN_FAILED = 'AUTH_LOGIN_FAILED';

  static readonly AUTH_INVALID_REFRESH_TOKEN = 'AUTH_INVALID_REFRESH_TOKEN';

  static readonly AUTH_REFRESH_FAILED = 'AUTH_REFRESH_FAILED';
  static readonly AUTH_TENANCY_SWITCH_FORBIDDEN =
    'AUTH_TENANCY_SWITCH_FORBIDDEN';
  static readonly AUTH_TENANCY_SWITCH_UNAVAILABLE =
    'AUTH_TENANCY_SWITCH_UNAVAILABLE';

  static readonly TENANT_CONTEXT_REQUIRED = 'TENANT_CONTEXT_REQUIRED';

  static readonly LOCALIDADE_INVALID_NAME = 'LOCALIDADE_INVALID_NAME';
  static readonly LOCALIDADE_INVALID_UF = 'LOCALIDADE_INVALID_UF';
  static readonly LOCALIDADE_INVALID_TYPE = 'LOCALIDADE_INVALID_TYPE';
  static readonly LOCALIDADE_NOT_FOUND = 'LOCALIDADE_NOT_FOUND';
  static readonly LOCALIDADE_REPOSITORY_FAILED = 'LOCALIDADE_REPOSITORY_FAILED';
  static readonly LOCALIDADE_ACCESS_FORBIDDEN = 'LOCALIDADE_ACCESS_FORBIDDEN';
  static readonly LOCALIDADE_CREATE_FAILED = 'LOCALIDADE_CREATE_FAILED';
  static readonly LOCALIDADE_UPDATE_FAILED = 'LOCALIDADE_UPDATE_FAILED';

  static readonly ORGAO_INVALID_NAME = 'ORGAO_INVALID_NAME';
  static readonly ORGAO_INVALID_LOCALIDADE = 'ORGAO_INVALID_LOCALIDADE';
  static readonly ORGAO_INVALID_TYPE = 'ORGAO_INVALID_TYPE';
  static readonly ORGAO_INVALID_EMAIL = 'ORGAO_INVALID_EMAIL';
  static readonly ORGAO_NOT_FOUND = 'ORGAO_NOT_FOUND';
  static readonly ORGAO_REPOSITORY_FAILED = 'ORGAO_REPOSITORY_FAILED';
  static readonly ORGAO_ACCESS_FORBIDDEN = 'ORGAO_ACCESS_FORBIDDEN';
  static readonly ORGAO_CREATE_FAILED = 'ORGAO_CREATE_FAILED';
  static readonly ORGAO_UPDATE_FAILED = 'ORGAO_UPDATE_FAILED';

  static readonly SETOR_INVALID_NAME = 'SETOR_INVALID_NAME';
  static readonly SETOR_INVALID_ORGAO = 'SETOR_INVALID_ORGAO';
  static readonly SETOR_NOT_FOUND = 'SETOR_NOT_FOUND';
  static readonly SETOR_REPOSITORY_FAILED = 'SETOR_REPOSITORY_FAILED';
  static readonly SETOR_ACCESS_FORBIDDEN = 'SETOR_ACCESS_FORBIDDEN';
  static readonly SETOR_CREATE_FAILED = 'SETOR_CREATE_FAILED';
  static readonly SETOR_UPDATE_FAILED = 'SETOR_UPDATE_FAILED';
}
