export const PESSOA_REPOSITORY = Symbol('PESSOA_REPOSITORY');
export const CREATE_PESSOA_SERVICE = Symbol('CREATE_PESSOA_SERVICE');
export const LIST_PESSOAS_SERVICE = Symbol('LIST_PESSOAS_SERVICE');
export const GET_PESSOA_SERVICE = Symbol('GET_PESSOA_SERVICE');
export const UPDATE_PESSOA_SERVICE = Symbol('UPDATE_PESSOA_SERVICE');
export const DELETE_PESSOA_SERVICE = Symbol('DELETE_PESSOA_SERVICE');
export const BUSCAR_PESSOAS_SERVICE = Symbol('BUSCAR_PESSOAS_SERVICE');
export const PROFISSIONAL_TECNICO_REPOSITORY = Symbol(
  'PROFISSIONAL_TECNICO_REPOSITORY',
);
export const CREATE_PROFISSIONAL_TECNICO_SERVICE = Symbol(
  'CREATE_PROFISSIONAL_TECNICO_SERVICE',
);
export const LIST_PROFISSIONAIS_TECNICOS_SERVICE = Symbol(
  'LIST_PROFISSIONAIS_TECNICOS_SERVICE',
);
export const BUSCAR_PROFISSIONAIS_TECNICOS_SERVICE = Symbol(
  'BUSCAR_PROFISSIONAIS_TECNICOS_SERVICE',
);
export const GET_PROFISSIONAL_TECNICO_SERVICE = Symbol(
  'GET_PROFISSIONAL_TECNICO_SERVICE',
);
export const UPDATE_PROFISSIONAL_TECNICO_SERVICE = Symbol(
  'UPDATE_PROFISSIONAL_TECNICO_SERVICE',
);
