export const PESSOA_REPOSITORY = Symbol('PESSOA_REPOSITORY');
export const CREATE_PESSOA_SERVICE = Symbol('CREATE_PESSOA_SERVICE');
export const LIST_PESSOAS_SERVICE = Symbol('LIST_PESSOAS_SERVICE');
