export const LOCALIDADE_REPOSITORY = Symbol('LOCALIDADE_REPOSITORY');
export const CREATE_LOCALIDADE_SERVICE = Symbol('CREATE_LOCALIDADE_SERVICE');
export const LIST_LOCALIDADES_SERVICE = Symbol('LIST_LOCALIDADES_SERVICE');
export const UPDATE_LOCALIDADE_SERVICE = Symbol('UPDATE_LOCALIDADE_SERVICE');
export const GET_LOCALIDADE_SERVICE = Symbol('GET_LOCALIDADE_SERVICE');
export const DELETE_LOCALIDADE_SERVICE = Symbol('DELETE_LOCALIDADE_SERVICE');
